name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --logger "trx;LogFileName=test-results.trx" --collect "Code Coverage" tests/Loan.Domain.Test/Loan.Domain.Test.csproj --no-restore --verbosity normal /p:CollectCoverage=true
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success()
      with:
        name: JEST Tests            
        path: ./tests/Loan.Domain.Test/TestResults/*.trx
        reporter: dotnet-trx        

    - name: Glob match
      uses: tj-actions/glob@v16
      id: glob
      with:
        files: |
          ./tests/Loan.Domain.Test/TestResults/**/*.coverage

    - name: Show all matching files
      run: |
        echo "${{ steps.glob.outputs.paths }}"
        
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ steps.glob.outputs.paths }}
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
